/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DocumensoApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "DocumensoDB": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "DocumensoDocumentBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DocumensoEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "DocumensoService": {
      "service": string
      "type": "sst.aws.Service"
    }
    "DocumensoVpc": {
      "type": "sst.aws.Vpc"
    }
    "EncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EncryptionSecondaryKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NextAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SigningCertificate": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SigningPassphrase": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}